[env]
platform = ststm32
platform_packages =
    platformio/toolchain-gccarmnoneeabi@^1.140201.0
    platformio/tool-stlink
board = genericSTM32H725RGVX
board_build.ldscript = ${platformio.boards_dir}/ldscripts/STM32H725XG_FLASH.ld
framework = arduino
upload_protocol = dfu
; upload_protocol = stlink
debug_tool = stlink
monitor_speed = 460800 
build_unflags =
    -std=gnu++17
build_flags =
    -std=gnu++20
    ; -flto ; Enable Link Time Optimization

; DEBUG
    ; -D DEBUG_SERIAL=Serial

; Hardware FPU
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=hard

; ARDUINO (BOARD SPECIFIC)
    -D ARDUINO_GENERIC_H72add5RGVX
    -D USE_PWR_DIRECT_SMPS_SUPPLY

; IRQ PRIORITY
    -D TIM_IRQ_PRIO=3

; PLATFORMIO
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_SCANF
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_USB_HIGHSPEED_FULLMODE

; FATFS MACROS
    "-D f_unmount(path)=f_mount(0, path, 0)"

; CMSIS RTOS V2
    -D configUSE_CMSIS_RTOS_V2=1
    -D configUSE_NEWLIB_REENTRANT=1
    -Wl,--wrap=delay

lib_deps =
    lib-xcore=https://gitlab.com/vtneil/lib-xcore.git
    FatFs=https://github.com/stm32duino/FatFs.git
    STM32SD=https://github.com/stm32duino/STM32SD.git
    STM32FreeRTOS=stm32duino/STM32duino FreeRTOS
    BMP581=sparkfun/SparkFun BMP581 Arduino Library
    BNO086=https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library
    stm32duino/STM32duino ISM6HG256X
    sparkfun/SparkFun u-blox GNSS v3
	robtillaart/INA236
    adafruit/Adafruit NeoPixel
    sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor
    stm32duino/STM32duino Low Power    
[env:MAIN]
build_flags =
    ${env.build_flags}
    -I ${PROJECT_INCLUDE_DIR}/config/Main
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<main/*.c>
    +<main/*.cpp>

[env:UAV]
build_flags =
    ${env.build_flags}
    -I ${PROJECT_INCLUDE_DIR}/config/UAV
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<uav/*.c>
    +<uav/*.cpp>

[env:test_path]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_path/*.c>
    +<test_path/*.cpp>

[env:test_sd]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_sd/*.c>
    +<test_sd/*.cpp>

[env:test_unit]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_unit/*.c>
    +<test_unit/*.cpp>

[env:test_servoa]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_servoa/*.c>
    +<test_servoa/*.cpp>

[env:test_servo_eeprom]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_servo_eeprom/*.c>
    +<test_servo_eeprom/*.cpp>

[env:test_gps]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_gps/*.c>
    +<test_gps/*.cpp>
