 [env]
platform = ststm32
platform_packages =
    platformio/toolchain-gccarmnoneeabi@^1.140201.0
    platformio/tool-stlink
board = genericSTM32H725RGVX
board_build.ldscript = ${platformio.boards_dir}/ldscripts/STM32H725XG_FLASH.ld
framework = arduino
upload_protocol = dfu
; upload_protocol = jlink
debug_tool = jlink
monitor_speed = 460800 
build_unflags =
    -std=gnu++17
build_flags =
    -std=gnu++20
    ; -flto ; Enable Link Time Optimization

; DEBUG
    ; -D DEBUG_SERIAL=Serial

; Hardware FPU
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=hard

; ARDUINO (BOARD SPECIFIC)
    -D ARDUINO_GENERIC_H725RGVX
    -D USE_PWR_DIRECT_SMPS_SUPPLY

; IRQ PRIORITY
    -D TIM_IRQ_PRIO=3

; PLATFORMIO
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
    -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_SCANF
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D PIO_FRAMEWORK_ARDUINO_USB_HIGHSPEED_FULLMODE

; FATFS MACROS
    "-D f_unmount(path)=f_mount(0, path, 0)"

; CMSIS RTOS V2
    -D configUSE_CMSIS_RTOS_V2=1
    -D configUSE_NEWLIB_REENTRANT=1
    -Wl,--wrap=delay

lib_deps =
    lib-xcore=https://gitlab.com/vtneil/lib-xcore.git
    FatFs=https://github.com/stm32duino/FatFs.git
    STM32SD=https://github.com/stm32duino/STM32SD.git
    STM32FreeRTOS=stm32duino/STM32duino FreeRTOS
    BMP581=sparkfun/SparkFun BMP581 Arduino Library
    BNO086=https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library
    stm32duino/STM32duino ISM6HG256X
    sparkfun/SparkFun u-blox GNSS v3
	robtillaart/INA236
    adafruit/Adafruit NeoPixel
    sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor
    
[env:main]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<main/*.c>
    +<main/*.cpp>

[env:test_path]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_path/*.c>
    +<test_path/*.cpp>

[env:test_imu]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_imu/*.c>
    +<test_imu/*.cpp>

[env:test_sd]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_sd/*.c>
    +<test_sd/*.cpp>

[env:test_i2c]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_i2c/*.c>
    +<test_i2c/*.cpp>

[env:test_bno]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_bno/*.c>
    +<test_bno/*.cpp>

[env:test_eeprom]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_eeprom/*.c>
    +<test_eeprom/*.cpp>

[env:test_servo]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_servo/*.c>
    +<test_servo/*.cpp>

[env:test_halfduplex]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_halfd/*.c>
    +<test_half/*.cpp>

[env:test_pid]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_pid/*.c>
    +<test_pid/*.cpp>

[env:test_xbee]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_xbee/*.c>
    +<test_xbee/*.cpp>

[env:test_unit]
build_src_filter =
    +<*.c>
    +<*.cpp>
    +<test_unit/*.c>
    +<test_unit/*.cpp>
build_flags =
    ${env.build_flags}
    -I${PROJECT_DIR}/include/config/Main